### ISSUE TITLE
SMARTS installed in programFiles directory leads to issues

### ISSUE THREAD

**Issue by cdeline** [NREL/pySMARTS#5]
I was getting a pretty un-informative error message:  PermissionError: [Errno 13] Permission denied: 'smarts295.inp.txt'

I tracked it down, and my SMARTSPATH in environment variables was pointing to a version of SMARTS on my /Program Files/ directory.  I don't have user authorization to make changes on that path.  Changing my SMARTSPATH to point to a version of SMARTS in my /Documents/ folder solved this issue.

It's possible that an instructive error could be included here - like 'File access denied. Make sure you have SMARTS installed in a directory that you have read/write privileges for'

**Comment by cdeline** [comment]
This is traced back to line 2458:


  File "C:\ProgramData\Anaconda3\lib\site-packages\pySMARTS\main.py", line 1450, in SMARTSSpectraZenAzm
    output = _smartsAll(CMNT, ISPR, SPR, ALTIT, HEIGHT, LATIT, IATMOS, ATMOS, RH, TAIR, SEASON, TDAY, IH2O, W, IO3, IALT, AbO3, IGAS, ILOAD, ApCH2O, ApCH4, ApCO, ApHNO2, ApHNO3, ApNO,ApNO2, ApNO3, ApO3, ApSO2, qCO2, ISPCTR, AEROS, ALPHA1, ALPHA2, OMEGL, GG, ITURB, TAU5, BETA, BCHUEP, RANGE, VISI, TAU550, IALBDX, RHOX, ITILT, IALBDG,TILT, WAZIM,  RHOG, WLMN, WLMX, SUNCOR, SOLARC, IPRT, WPMN, WPMX, INTVL, IOUT, ICIRC, SLOPE, APERT, LIMIT, ISCAN, IFILT, WV1, WV2, STEP, FWHM, ILLUM,IUV, IMASS, ZENITH, AZIM, ELEV, AMASS, YEAR, MONTH, DAY, HOUR, LONGIT, ZONE, DSTEP)

  File "C:\ProgramData\Anaconda3\lib\site-packages\pySMARTS\main.py", line 2458, in _smartsAll
    f = open('smarts295.inp.txt', 'w')

PermissionError: [Errno 13] Permission denied: 'smarts295.inp.txt'

**Comment by shirubana** [comment]
fixed
