### ISSUE TITLE
code problem-Could not find SMARTS2 executable.AttributeError: 'NoneType' object has no attribute 'keys'

### ISSUE THREAD

**Issue by Huanghao-stephen** [NREL/pySMARTS#6]
![image](https://github.com/NREL/pySMARTS/assets/88754783/c3e95eda-214d-43e9-9265-1c44732b243f)

**Comment by shirubana** [comment]
As per the instructions: 
"Please note that you will be responsible of downloading SMARTS 2.9.5 from NREL website, and setting `SMARTSPATH` environment variable to the location of the executable."
